[project]
name = "vtkwriter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pyvista>=0.46.4",
    "vtk>=9.5.2",
    "websockets>=15.0.1",
]
